config/routes.rb
Rails.application.routes.draw do
  resources :sightings do
    get :get_events, on: :collection
    end

  resources :animals

  root 'animals#index'

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  has_many :sightings
  validates :common_name, length: { minimum: 2 }
  validates :latin_name, uniqueness: true
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :animal
  validates :animal, presence: true

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
    @animal = Animal.first
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end


  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.sightings.destroy_all
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:common_name, :latin_name, :location)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting, only: [:show, :edit, :update, :destroy]

  # GET /sightings
  # GET /sightings.json

  def index
    # if start date is not empty, then find the sighting date between start date and end date + find the region and render it on the index.html.erb page...else find all sighting dates
    if !params[:start_date].nil? && !params[:end_date].nil? &&   !params[:start_date].strip.empty? &&      !params[:end_date].strip.empty?
        @sightings = Sighting.where(date:params[:start_date]..params[:end_date], region: params[:region])
        render('sightings/index.html.erb')
      else
        @sightings = Sighting.all
      end
    end


 def get_events
     @sightings = Sighting.all
     events = []
     @sightings.each do |sighting|
       events << { id: sighting.id, title:sighting.animal.common_name, start: DateTime.new(sighting.date.year, sighting.date.month, sighting.date.day, sighting.time.hour, sighting.time.min, sighting.time.sec).to_s, url:"/sightings/" + sighting.id.to_s
       }
     end
     render :json => events.to_json
   end

  # GET /sightings/1
  # GET /sightings/1.json
  def show
  end

  # GET /sightings/new
  def new
    @sighting = Sighting.new
    @animals_for_select = Animal.all.map do |animal|
    [animal.common_name, animal.id]
   end
  #  @sighting.animal = animal.first
 end

  # GET /sightings/1/edit
  def edit
    @animals_for_select = Animal.all.map do |animal|
    [animal.common_name, animal.id]
    end
  end

  # POST /sightings
  # POST /sightings.json
  def create
    @sighting = Sighting.new(sighting_params)

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to @sighting, notice: 'Sighting was successfully created.' }
        format.json { render :show, status: :created, location: @sighting }
      else
        format.html { render :new }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sightings/1
  # PATCH/PUT /sightings/1.json
  def update
    respond_to do |format|
      if @sighting.update(sighting_params)
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sighting }
      else
        format.html { render :edit }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting.destroy
    respond_to do |format|
      format.html { redirect_to sightings_url, notice: 'Sighting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sighting
      @sighting = Sighting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sighting_params
      params.require(:sighting).permit(:date, :time, :latitude, :longitude, :region, :animal_id, :start_date, :end_date)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation text-center">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :common_name %><br>
    <%= f.text_field :common_name %>
  </div>
  <div class="field">
    <%= f.label :latin_name %><br>
    <%= f.text_field :latin_name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/_sighting.html.erb
<ul>
  <li>Date: <%= sighting.date %></li>
  <li>Time: <%= sighting.time %></li>
  <li>Longitude: <%= sighting.longitude %></li>
  <li>Latitude: <%= sighting.latitude %></li>
  <li>Region: <%= sighting.region %></li>
</ul>
<hr>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!-- end of bootstrap  -->


<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="http://www.hd-wallpapersdownload.com/script/bulk-upload/wildlife-hd-photography-hd-wallpaper.jpg">
    </div>

    <div class="item">
      <img src="http://wallpapersviral.com/wp-content/uploads/2016/08/wildlife-animal-wallpaper-3.jpg">
    </div>

    <div class="item">
      <img src="http://wallpapercave.com/wp/7sEaAra.jpg">
    </div>

    <div class="item">
      <img src="http://wall.rimbuz.com/wp-content/uploads/Lion-Black-and-White-HD-Photo-Wallpapers.jpg">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="row col-sm-12 text-center">
  <h1>Wild Watch - Portland, Oregon Wildlife Tracker</h1>
</div>

<div class="box">
  <table id="table" class="table">
    <thead>
      <tr>
        <th>Common name</th>
        <th>Latin name</th>
        <th>Location</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  </div>

  <tbody id="animal_list">
    <% @animals.each do |animal| %>
    <tr>
      <td><%= animal.common_name %></td>
      <td><%= animal.latin_name %></td>
      <td><%= animal.location %></td>
      <td><%= link_to 'Show', animal %></td>
      <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
      <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="row col-sm-12 text-center">
  <button type="button"><%= link_to 'New Animal', new_animal_path %></button>
</div>

<hr>

<div class="row col-sm-12 text-center">
  <button type="button"><a href="http://localhost:3000/sightings">Register Animal Sighting</a></button>
</div>

<br>

<div class="row col-sm-12 text-center">
  <br>
  <p>
    <input type="text" name="animal[common_name]" placeholder="Name" id="animal_common_name"/>
    <input type="text" name="animal[latin_name]" placeholder="Latin Name"id="animal_latin_name"/>
    <input type="text" name="animal[location]" placeholder="Location" id="animal_location"/>
    <input type="hidden" name="animal[animal_id]" id="animal_id" value="<%=@animal.id%>"/>
    <button id="add_new_animal_button">Add New Animal</button>
  </p>
</div>

<hr>

<div class="row col-sm-12 text-center" id="IUCN">
  <h2>Spotted an Endangered Animal?</h2>
  <h3>
    contact <a href="http://www.iucnredlist.org/" target="_blank"> <%= image_tag "IUCN_Red_List.svg.png", :id=> "logo" %></a>
  </h3>
</div>

<hr>

<!-- begin wwww.htmlcommentbox.com -->

<div class="row col-sm-12 text-center">
<div id="HCB_comment_box"><a href="http://www.htmlcommentbox.com">Widget</a> is loading comments...</div>
 <link rel="stylesheet" type="text/css" href="//www.htmlcommentbox.com/static/skins/bootstrap/twitter-bootstrap.css?v=0" />
 <script type="text/javascript" id="hcb"> if(!window.hcb_user){hcb_user={};} (function(){var s=document.createElement("script"), l=hcb_user.PAGE || (""+window.location).replace(/'/g,"%27"), h="//www.htmlcommentbox.com";s.setAttribute("type","text/javascript");s.setAttribute("src", h+"/jread?page="+encodeURIComponent(l).replace("+","%2B")+"&opts=16862&num=10&ts=1474065845080");if (typeof s!="undefined") document.getElementsByTagName("head")[0].appendChild(s);})();
 </script>
<!-- end www.htmlcommentbox.com -->
</div>


<hr>

<div class="row col-sm-12 text-center">
  <footer class="row col-sm-12 text-center">
    <%= image_tag "Forest_service.png", :id=> "logo" %>
    Made with &hearts; by	Remy and Adam
    <%= image_tag "INaturalist_logo.png", :id=> "logo" %>
    <h6>This is not a product of the Oregon Forest Service, IUCN, or iNaturalist</h6>
  </footer>
</div>

app/views/animals/new.html.erb
<div style="display:flex;justify-content:center;align-items:center;">
  <div id="new_animal" class="text-center center-block">
    <h1>New Animal</h1>
    <%= render 'form' %>
    <br>
    <button> <%= link_to 'Back', animals_path %> </button>
  </div>
</div>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Common name:</strong>
  <%= @animal.common_name %>
</p>

<p>
  <strong>Latin name:</strong>
  <%= @animal.latin_name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @animal.location %>
</p>

<p id="sighting_list">
  <ul>
    <%= render partial: "sighting", collection: @animal.sightings %>
  </ul>
</p>

<p>
  <input type="date" name="sighting[date]" placeholder="Date" id="sighting_date"/>
  <input type="time" name="sighting[time]" placeholder="Time"id="sighting_time"/>
  <input type="number" name="sighting[latitude]" placeholder="Lat" id="sighting_latitude"/>
  <input type="number" name="sighting[longitude]" placeholder="Long" id="sighting_longitude"/>
  <input type="hidden" name="sighting[animal_id]" id="animal_id" value="<%=@animal.id%>"/>
  <div class="field">
  <%= select(:sighting, :region, options_for_select([['north', 'north'],['south', 'south'],['east', 'east'],['west', 'west']])) %>
  </div>
  <button id="add_new_sighting_button">Add new Sighting</button>
</p>



<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <!-- end of bootstrap  -->

  <title>Wildlifeapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sightings/_form.html.erb
<%= form_for(@sighting) do |f| %>
  <% if @sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% @sighting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
  <%= select(:sighting, :region, options_for_select([['north', 'north'],['south', 'south'],['east', 'east'],['west', 'west']])) %>
  </div>
  <div class="field">
  <%= select(:sighting, :animal_id, @animals_for_select) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sightings/edit.html.erb
<h1>Editing Sighting</h1>

<%= render 'form' %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

app/views/sightings/index.html.erb
<p id="notice"><%= notice %></p>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!-- end of bootstrap  -->

<div class="row col-sm-12 text-center">
<h1>Animal Sightings</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Region</th>
      <th>Animal</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.date %></td>
        <td><%= sighting.time.strftime("%H:%M") %></td>
        <td><%= sighting.latitude %></td>
        <td><%= sighting.longitude %></td>
        <td><%= sighting.region %></td>
        <td><%= sighting.animal.common_name %></td>
        <td><%= link_to 'Show', sighting %></td>
        <td><%= link_to 'Edit', edit_sighting_path(sighting) %></td>
        <td><%= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure you want to destroy this animal?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<div class="row col-sm-12 text-center">
  <form action="/sightings" method="get">
    <label for="start_date">Start date</label>
    <input id="start_date" name="start_date" type="date">
    <label for="end_date">End date</label>
    <input id="end_date" name="end_date" type="date">
    <div class="field">
      <br>
      <label for="region">Region</label>
      <%= select_tag("region", options_for_select([['north', 'north'],['south', 'south'],['east', 'east'],['west', 'west']])) %>
    </div>
    <br>
    <button>Run report</button>
  </form>
</div>
<hr>

<div class="row col-sm-12 text-center">
  <br>
<button type="button"><%= link_to 'New Sighting', new_sighting_path %></button>

<div id="calendar"></div>

<hr>
<button type="button"><a href="http://localhost:3000/animals">Return To Home Page</a></button>
</div>

app/views/sightings/new.html.erb
<h1>New Sighting</h1>

<%= render 'form' %>

<%= link_to 'Back', sightings_path %>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @sighting.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @sighting.time.strftime("%R") %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @sighting.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @sighting.longitude %>
</p>

<p>
  <strong>Region:</strong>
  <%= @sighting.region %>
</p>


<p>
  <strong>Animal:</strong>
  <%= @sighting.animal.common_name %>
</p>


<button><%= link_to 'Edit', edit_sighting_path(@sighting) %> </button>
<br>
<br>
<button> <%= link_to 'Back', sightings_path %> </button>